### ISSUE TITLE
FalcomFontCreator

### ISSUE THREAD

**Issue by RyukoM4701** [Trails-Research-Group/Doc#4]
Apparently, FalcomFontCreator doesn't exist anymore, it's either deleted or made private by the owner. 
I didn't really have any means of communication with them other than here so I want to ask if there is any chance it can be brought back again because I think I might need it.

This is kinda out of topic but my language has some letters that are not in the game or in the font file the game uses so I wanted to try to possibly bring them back but I have no tools to open the font file of the game. (Ys VIII)

**Comment by TwnKey** [comment]
https://github.com/TwnKey/FalcomFontCreator
Avaiable again here
